### ISSUE TITLE
D-Scanner: Unused parameters

### ISSUE THREAD

**Issue by belka-ew** [dlang/ecotasks#3]
I'm (under contract from Funkwerk AG) working on the D-Scanner issues right now. Specifically, I plan to tackle issues https://github.com/dlang-community/D-Scanner/issues/765, and https://github.com/dlang-community/D-Scanner/issues/613.

**Comment by belka-ew** [comment]
- https://github.com/dlang-community/D-Scanner/pull/768
- https://github.com/dlang-community/D-Scanner/pull/769

**Comment by mdparker** [comment]
Thanks!
