### ISSUE TITLE
Funkwerk: dub for internal use

### ISSUE THREAD

**Issue by FeepingCreature** [dlang/ecotasks#4]
We're trying to transition from a homebrew build solution to dub for builds and dependency checking. As such, because we have a lot of internal repos who are heavily interdependent, the plan is to create a way to combine dub with git submodules. 

Why submodules? Due to our use of microservices, often a change in one project is developed in tandem with a corresponding change in another. As such, we would like the ability to edit both repositories locally, simultaneously (ie. submodules), then commit the changes to two branches and run those on the build server, preferably without having to change the configuration and vitally without losing the ability to still specify and check versions, and use the repos in other submodules.

For comparison, a workflow using explicit branches would require a lot of "make change, git commit, git push, change folder, git pull, test change, go back", etc, which would be cumbersome. And dub local overrides would break on Jenkins.

More details for the approach I've developed are on the corresponding dub PR: https://github.com/dlang/dub/pull/1780 . I think this workflow is important for internal project use with internal dependencies that simultaneously need lightweight modification and sophisticated version checking.

Unfortunately, the PR seems to be stalled...

**Comment by mdparker** [comment]
The PR was merged, so I think we can close this.
