### ISSUE TITLE
Last 3 dfmt issues fixed by Funkwerk

### ISSUE THREAD

**Issue by belka-ew** [dlang/ecotasks#5]
There 3 issues I fixed in dfmt on behalf of Funkwerk:

- https://github.com/dlang-community/dfmt/issues/454
- https://github.com/dlang-community/dfmt/issues/452
- https://github.com/dlang-community/dfmt/issues/448

Sorry that I'm writing this afterwards, my fault, I completely forgot it.

**Comment by mdparker** [comment]
No worries. Thanks a lot for the effort!
