### ISSUE TITLE
Funkwerk: dfmt --keep_line_breaks  feature

### ISSUE THREAD

**Issue by belka-ew** [dlang/ecotasks#6]
One more dfmt issue fixed by Funkwerk:
https://github.com/dlang-community/dfmt/pull/471 (Pull request).

Fixed issues:
- https://github.com/dlang-community/dfmt/issues/7
- https://github.com/dlang-community/dfmt/issues/463
- https://github.com/dlang-community/dfmt/issues/254
- https://github.com/dlang-community/dfmt/issues/270

**Comment by mdparker** [comment]
Thanks!
